export const discriminatorDefaults: Record<string, Record<string, unknown>> = {
	damage: {
		type: "damage",
		target: "enemy",
		damageType: "slashing",
		dice: "1d6",
		requiresAttackRoll: false,
	},
	attackDamage: { type: "attackDamage", target: "enemy", multiplier: 1, attackRiders: [] },
	heal: { type: "heal", target: "self", dice: "1d6" },
	applyStatus: { type: "applyStatus", target: "enemy", statusId: "stunned", durationTurns: 1 },
	removeStatus: {
		type: "removeStatus",
		target: "self",
		statusIds: ["stunned"],
		allNegative: false,
		allPositive: false,
	},
	modifyStat: {
		type: "modifyStat",
		target: "self",
		stat: "armourClass",
		value: 1,
		durationTurns: 1,
	},
	modifyHealing: { type: "modifyHealing", target: "self", multiplier: 1, durationTurns: 1 },
	modifyDamage: {
		type: "modifyDamage",
		target: "self",
		operation: "add",
		value: 1,
		durationTurns: 1,
	},
	modifyDamageTaken: {
		type: "modifyDamageTaken",
		target: "self",
		operation: "add",
		value: 1,
		durationTurns: 1,
	},
	modifyDamageAffinity: {
		type: "modifyDamageAffinity",
		target: "self",
		affinity: "resistance",
		operation: "add",
		damageType: "fire",
		durationTurns: 1,
	},
	modifyRoll: {
		type: "modifyRoll",
		target: "self",
		roll: "attack",
		mode: "advantage",
		durationTurns: 1,
	},
	damageOverTime: {
		type: "damageOverTime",
		target: "enemy",
		damageType: "fire",
		dice: "1d4",
		durationTurns: 1,
	},
	healOverTime: { type: "healOverTime", target: "self", dice: "1d4", durationTurns: 1 },
	shield: { type: "shield", target: "self", amount: 1, durationTurns: 1 },
};

export const modifierDefaults: Record<string, Record<string, unknown>> = {
	modifyStat: { type: "modifyStat", stat: "armourClass", value: 1 },
	modifyHealing: { type: "modifyHealing", multiplier: 1 },
	modifyDamage: { type: "modifyDamage", operation: "add", value: 1 },
	modifyDamageTaken: { type: "modifyDamageTaken", operation: "add", value: 1 },
	modifyDamageAffinity: {
		type: "modifyDamageAffinity",
		affinity: "resistance",
		operation: "add",
		damageType: "fire",
	},
};

export const optionsByField: Record<string, readonly string[]> = {
	target: ["self", "enemy"],
	pool: [
		"assassin",
		"barbarian",
		"cleric",
		"common",
		"mage",
		"occultist",
		"rogue",
		"unique",
		"warlock",
		"warrior",
	],
	hitDie: ["1d4", "1d6", "1d8", "1d10", "1d12"],
	weaponType: [
		"axe",
		"bow",
		"club",
		"crossbow",
		"dagger",
		"hammer",
		"mace",
		"spear",
		"staff",
		"sword",
		"wand",
	],
	rank: ["normal", "elite", "boss"],
	tactic: ["default", "aggressive", "defensive", "caster", "random", "conceder"],
	damageType: [
		"acid",
		"cold",
		"crushing",
		"fire",
		"lightning",
		"necrotic",
		"piercing",
		"poison",
		"radiant",
		"slashing",
	],
	attribute: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
	timing: ["onHit", "onCrit"],
	operation: ["add", "multiply", "remove"],
	affinity: ["resistance", "immunity", "vulnerability"],
	position: ["prefix", "suffix"],
	rarity: ["common", "uncommon", "rare", "epic", "legendary"],
	handedness: ["oneHanded", "twoHanded"],
	range: ["melee", "ranged"],
	slot: ["body", "shield", "helmet", "gloves", "boots", "belt", "amulet", "ring"],
};
