export const discriminatorDefaults: Record<string, Record<string, unknown>> = {
	damage: {
		type: "damage",
		target: "enemy",
		damageType: "slashing",
		damageClass: "physical",
		dice: "1d6",
		requiresAttackRoll: false,
	},
	attackDamage: { type: "attackDamage", target: "enemy", multiplier: 1, attackRiders: [] },
	heal: { type: "heal", target: "self", dice: "1d6" },
	applyStatus: {
		type: "applyStatus",
		target: "enemy",
		statusId: "stunned",
		duration: { unit: "turns", value: 1 },
	},
	removeStatus: {
		type: "removeStatus",
		target: "self",
		statusIds: ["stunned"],
		allNegative: false,
		allPositive: false,
	},
	modifyStat: {
		type: "modifyStat",
		target: "self",
		stat: "armourClass",
		value: 1,
		duration: { unit: "turns", value: 1 },
	},
	modifyHealing: {
		type: "modifyHealing",
		target: "self",
		multiplier: 1,
		duration: { unit: "turns", value: 1 },
	},
	modifyDamage: {
		type: "modifyDamage",
		target: "self",
		operation: "add",
		value: 1,
		duration: { unit: "turns", value: 1 },
	},
	modifyDamageTaken: {
		type: "modifyDamageTaken",
		target: "self",
		operation: "add",
		value: 1,
		duration: { unit: "turns", value: 1 },
	},
	modifyDamageAffinity: {
		type: "modifyDamageAffinity",
		target: "self",
		affinity: "resistance",
		operation: "add",
		damageType: "fire",
		duration: { unit: "turns", value: 1 },
	},
	modifyRoll: {
		type: "modifyRoll",
		target: "self",
		roll: "attack",
		mode: "advantage",
		duration: { unit: "turns", value: 1 },
	},
	damageOverTime: {
		type: "damageOverTime",
		target: "enemy",
		damageType: "fire",
		damageClass: "magical",
		dice: "1d4",
		duration: { unit: "turns", value: 1 },
	},
	healOverTime: {
		type: "healOverTime",
		target: "self",
		dice: "1d4",
		duration: { unit: "turns", value: 1 },
	},
	shield: { type: "shield", target: "self", amount: 1, duration: { unit: "turns", value: 1 } },
};

export const modifierDefaults: Record<string, Record<string, unknown>> = {
	modifyStat: { type: "modifyStat", stat: "armourClass", value: 1 },
	modifyHealing: { type: "modifyHealing", multiplier: 1 },
	modifyDamage: { type: "modifyDamage", operation: "add", value: 1 },
	modifyDamageTaken: { type: "modifyDamageTaken", operation: "add", value: 1 },
	modifyDamageAffinity: {
		type: "modifyDamageAffinity",
		affinity: "resistance",
		operation: "add",
		damageType: "fire",
	},
};
