import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_dagger",
	name: "Dagger",
	basePrice: 80,
	type: "weapon",
	weaponType: "dagger",
	handedness: "oneHanded",
	attackRange: "melee",
	damage: {
		dice: "1d4",
		type: "piercing",
		damageClass: "physical",
		attribute: "dexterity",
	},
	iconPool: [
		"items/weapons/daggers/Dagger_01.png",
		"items/weapons/daggers/Dagger_02.png",
		"items/weapons/daggers/Dagger_03.png",
		"items/weapons/daggers/Dagger_04.png",
		"items/weapons/daggers/Dagger_05.png",
		"items/weapons/daggers/Dagger_06.png",
		"items/weapons/daggers/Dagger_07.png",
		"items/weapons/daggers/Dagger_08.png",
		"items/weapons/daggers/Dagger_09.png",
		"items/weapons/daggers/Dagger_11.png",
		"items/weapons/daggers/Dagger_13.png",
		"items/weapons/daggers/Dagger_17.png",
		"items/weapons/daggers/Dagger_20.png",
		"items/weapons/daggers/Dagger_21.png",
		"items/weapons/daggers/Dagger_22.png",
		"items/weapons/daggers/Dagger_23.png",
		"items/weapons/daggers/Dagger_24.png",
		"items/weapons/daggers/Dagger_25.png",
		"items/weapons/daggers/Dagger_26.png",
		"items/weapons/daggers/Dagger_28.png",
		"items/weapons/daggers/Dagger_31.png",
	],
	tags: [],
});
