import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_longsword",
	name: "Longsword",
	basePrice: 50,
	type: "weapon",
	weaponType: "sword",
	handedness: "oneHanded",
	range: "melee",
	damage: {
		dice: "1d6",
		type: "slashing",
		attribute: "strength",
	},
	iconPool: [
		"items/weapons/swords/Sword_0.png",
		"items/weapons/swords/Sword_01.png",
		"items/weapons/swords/Sword_02.png",
		"items/weapons/swords/Sword_03.png",
		"items/weapons/swords/Sword_04.png",
		"items/weapons/swords/Sword_05.png",
		"items/weapons/swords/Sword_06.png",
		"items/weapons/swords/Sword_08.png",
		"items/weapons/swords/Sword_10.png",
		"items/weapons/swords/Sword_11.png",
		"items/weapons/swords/Sword_15.png",
		"items/weapons/swords/Sword_16.png",
		"items/weapons/swords/Sword_17.png",
		"items/weapons/swords/Sword_18.png",
		"items/weapons/swords/Sword_19.png",
		"items/weapons/swords/Sword_20.png",
		"items/weapons/swords/Sword_21.png",
		"items/weapons/swords/Sword_22.png",
		"items/weapons/swords/Sword_29.png",
		"items/weapons/swords/Sword_30.png",
		"items/weapons/swords/Sword_31.png",
		"items/weapons/swords/Sword_32.png",
		"items/weapons/swords/Sword_34.png",
		"items/weapons/swords/Sword_35.png",
		"items/weapons/swords/Sword_37.png",
		"items/weapons/swords/Sword_38.png",
		"items/weapons/swords/Sword_40.png",
		"items/weapons/swords/Sword_41.png",
		"items/weapons/swords/Sword_42.png",
		"items/weapons/swords/Sword_48.png",
		"items/weapons/swords/Sword_49.png",
		"items/weapons/swords/Sword_51.png",
		"items/weapons/swords/Sword_52.png",
		"items/weapons/swords/Sword_54.png",
		"items/weapons/swords/Sword_64.png",
		"items/weapons/swords/Sword_65.png",
	],
	tags: [],
});
