import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_longbow",
	name: "Longbow",
	basePrice: 110,
	type: "weapon",
	weaponType: "bow",
	handedness: "twoHanded",
	attackRange: "ranged",
	damage: {
		dice: "1d8",
		type: "piercing",
		damageClass: "physical",
		attribute: "dexterity",
	},
	iconPool: [
		"items/weapons/bows/Bow_01.png",
		"items/weapons/bows/Bow_02.png",
		"items/weapons/bows/Bow_03.png",
		"items/weapons/bows/Bow_04.png",
		"items/weapons/bows/Bow_05.png",
		"items/weapons/bows/Bow_06.png",
		"items/weapons/bows/Bow_07.png",
		"items/weapons/bows/Bow_08.png",
		"items/weapons/bows/Bow_09.png",
		"items/weapons/bows/Bow_10.png",
		"items/weapons/bows/Bow_11.png",
		"items/weapons/bows/Bow_12.png",
		"items/weapons/bows/Bow_13.png",
		"items/weapons/bows/Bow_14.png",
		"items/weapons/bows/Bow_v2_01.png",
		"items/weapons/bows/Bow_v2_02.png",
		"items/weapons/bows/Bow_v2_03.png",
		"items/weapons/bows/Bow_v2_04.png",
	],
	tags: [],
});
