import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_spear",
	name: "Spear",
	basePrice: 40,
	type: "weapon",
	weaponType: "spear",
	handedness: "twoHanded",
	range: "melee",
	damage: {
		dice: "1d8",
		type: "piercing",
		attribute: "strength",
	},
	iconPool: [
		"items/weapons/spears/Spear_01.png",
		"items/weapons/spears/Spear_02.png",
		"items/weapons/spears/Spear_03.png",
		"items/weapons/spears/Spear_04.png",
		"items/weapons/spears/Spear_05.png",
		"items/weapons/spears/Spear_06.png",
		"items/weapons/spears/Spear_10.png",
		"items/weapons/spears/Spear_11.png",
		"items/weapons/spears/Spear_13.png",
		"items/weapons/spears/Spear_16.png",
		"items/weapons/spears/Spear_17.png",
		"items/weapons/spears/Spear_21.png",
		"items/weapons/spears/Spear_v2_03.png",
		"items/weapons/spears/Spear_v2_04.png",
		"items/weapons/spears/Spear_v2_06.png",
		"items/weapons/spears/Spear_v2_07.png",
		"items/weapons/spears/Spear_v2_08.png",
		"items/weapons/spears/Spear_v2_09.png",
		"items/weapons/spears/Spear_v2_10.png",
	],
	tags: [],
});
