import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_staff",
	name: "Staff",
	basePrice: 105,
	type: "weapon",
	weaponType: "staff",
	handedness: "twoHanded",
	range: "melee",
	damage: {
		dice: "1d8",
		type: "crushing",
		attribute: "strength",
	},
	iconPool: [
		"items/weapons/staves/staff_1.png",
		"items/weapons/staves/staff_2.png",
		"items/weapons/staves/staff_3.png",
		"items/weapons/staves/staff_4.png",
		"items/weapons/staves/staff_5.png",
		"items/weapons/staves/staff_11.png",
		"items/weapons/staves/staff_12.png",
		"items/weapons/staves/Staff_51.png",
		"items/weapons/staves/Staff_52.png",
		"items/weapons/staves/Staff_53.png",
		"items/weapons/staves/Staff_54.png",
		"items/weapons/staves/Staff_v2_08.png",
		"items/weapons/staves/Staff_v2_09.png",
		"items/weapons/staves/Staff_v2_10.png",
		"items/weapons/staves/Staff_v2_13.png",
		"items/weapons/staves/Staff_v2_14.png",
		"items/weapons/staves/Staff_v2_15.png",
		"items/weapons/staves/Staff_v2_16.png",
		"items/weapons/staves/Staff_v2_18.png",
	],
	tags: [],
});
