import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_warhammer",
	name: "Warhammer",
	basePrice: 135,
	type: "weapon",
	weaponType: "warhammer",
	handedness: "twoHanded",
	range: "melee",
	damage: {
		dice: "1d10",
		type: "crushing",
		attribute: "strength",
	},
	iconPool: [
		"items/weapons/hammers/Hammer_01.png",
		"items/weapons/hammers/Hammer_02.png",
		"items/weapons/hammers/Hammer_03.png",
		"items/weapons/hammers/Hammer_04.png",
		"items/weapons/hammers/Hammer_05.png",
		"items/weapons/hammers/Hammer_06.png",
		"items/weapons/hammers/Hammer_07.png",
		"items/weapons/hammers/Hammer_08.png",
		"items/weapons/hammers/Hammer_09.png",
		"items/weapons/hammers/Hammer_10.png",
		"items/weapons/hammers/Hammer_11.png",
		"items/weapons/hammers/Hammer_12.png",
		"items/weapons/hammers/Hammer_17.png",
		"items/weapons/hammers/Hammer_18.png",
		"items/weapons/hammers/Hammer_19.png",
		"items/weapons/hammers/Hammer_20.png",
		"items/weapons/hammers/Hammer_30.png",
		"items/weapons/hammers/Hammer_32.png",
		"items/weapons/hammers/Hammer_33.png",
		"items/weapons/hammers/Hammer_34.png",
		"items/weapons/hammers/Hammer_35.png",
	],
	tags: [],
});
