import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_boots",
	name: "Boots",
	basePrice: 120,
	type: "armour",
	slot: "boots",
	iconPool: [
		"items/armour/boots/Boots_01_common.png",
		"items/armour/boots/Boots_02.png",
		"items/armour/boots/Boots_03.png",
		"items/armour/boots/Boots_04.png",
		"items/armour/boots/Boots_05.png",
		"items/armour/boots/Boots_06.png",
		"items/armour/boots/Boots_07.png",
		"items/armour/boots/Boots_08.png",
		"items/armour/boots/Boots_09.png",
		"items/armour/boots/Boots_10.png",
		"items/armour/boots/Boots_36.png",
		"items/armour/boots/Boots_37.png",
		"items/armour/boots/Boots_38.png",
		"items/armour/boots/Boots_39.png",
		"items/armour/boots/Boots_40.png",
		"items/armour/boots/Boots_43.png",
		"items/armour/boots/Boots_44.png",
		"items/armour/boots/Boots_45.png",
	],
	tags: [],
});
