import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_helmet",
	name: "Helmet",
	basePrice: 20,
	type: "armour",
	slot: "helmet",
	iconPool: [
		"items/armour/helms/Helm_01_guard.png",
		"items/armour/helms/Helm_04.png",
		"items/armour/helms/Helm_05_Crusader.png",
		"items/armour/helms/Helm_06.png",
		"items/armour/helms/Helm_07_footman.png",
		"items/armour/helms/Helm_11_footman.png",
		"items/armour/helms/Helm_12_broken.png",
		"items/armour/helms/Helm_18.png",
		"items/armour/helms/Helm_20.png",
		"items/armour/helms/Helm_21_spearman.png",
		"items/armour/helms/Helm_22_spearman.png",
		"items/armour/helms/Helm_23.png",
		"items/armour/helms/Helm_26.png",
		"items/armour/helms/Helm_40.png",
		"items/armour/helms/Helm_42.png",
		"items/armour/helms/Helm_43_knight.png",
		"items/armour/helms/Helm_49_knight.png",
		"items/armour/helms/Helm_51.png",
		"items/armour/helms/HelmS.png",
		"items/armour/helms/HelmS2.png",
	],
	tags: [],
});
