import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_necklace",
	name: "Necklace",
	basePrice: 130,
	type: "armour",
	slot: "amulet",
	iconPool: [
		"items/armour/neck/necklace_01_cross.png",
		"items/armour/neck/necklace_02.png",
		"items/armour/neck/necklace_03.png",
		"items/armour/neck/necklace_04_love.png",
		"items/armour/neck/necklace_05.png",
		"items/armour/neck/necklace_06.png",
		"items/armour/neck/necklace_11_fourcolors.png",
		"items/armour/neck/necklace_12goldeye.png",
		"items/armour/neck/necklace_13.png",
		"items/armour/neck/necklace_14.png",
		"items/armour/neck/necklace_15.png",
		"items/armour/neck/necklace_16.png",
		"items/armour/neck/necklace_17.png",
		"items/armour/neck/necklace_18.png",
		"items/armour/neck/necklace_19.png",
		"items/armour/neck/necklace_20.png",
		"items/armour/neck/necklace_21_doll.png",
		"items/armour/neck/necklace_22_shaman.png",
		"items/armour/neck/necklace_23_princess.png",
		"items/armour/neck/necklace_24_crystalBlue.png",
		"items/armour/neck/necklace_25_crystalGreen.png",
		"items/armour/neck/necklace_26_crystalPurple.png",
		"items/armour/neck/necklace_27_ship.png",
		"items/armour/neck/necklace_28_Special.png",
		"items/armour/neck/necklace_29.png",
		"items/armour/neck/necklace_30_scull.png",
		"items/armour/neck/necklace_31.png",
		"items/armour/neck/necklace_32.png",
		"items/armour/neck/necklace_33.png",
		"items/armour/neck/necklace_34Blackdrop.png",
		"items/armour/neck/necklace_35_purple.png",
		"items/armour/neck/necklace_36_gold.png",
	],
	tags: [],
});
