import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_ring",
	name: "Ring",
	basePrice: 90,
	type: "armour",
	slot: "ring",
	iconPool: [
		"items/armour/ring/Ring_04.png",
		"items/armour/ring/Ring_05.png",
		"items/armour/ring/Ring_06_silvergreen.png",
		"items/armour/ring/Ring_07.png",
		"items/armour/ring/Ring_08.png",
		"items/armour/ring/Ring_09.png",
		"items/armour/ring/Ring_10.png",
		"items/armour/ring/Ring_17Silver_redEye.png",
		"items/armour/ring/Ring_18_silverPurple.png",
		"items/armour/ring/Ring_19_water.png",
		"items/armour/ring/Ring_20.png",
		"items/armour/ring/Ring_21_redgold.png",
		"items/armour/ring/Ring_22.png",
		"items/armour/ring/Ring_23.png",
		"items/armour/ring/Ring_24_warlock.png",
		"items/armour/ring/Ring_25.png",
		"items/armour/ring/Ring_26.png",
		"items/armour/ring/Ring_27_goldGreen.png",
		"items/armour/ring/Ring_28.png",
		"items/armour/ring/Ring_29.png",
		"items/armour/ring/Ring_30.png",
		"items/armour/ring/Ring_31.png",
		"items/armour/ring/Ring_32.png",
		"items/armour/ring/Ring_33.png",
	],
	tags: [],
});
