import { buildItemBase } from "../../builders/buildItemBase";

export default buildItemBase({
	id: "base_shield",
	name: "Shield",
	basePrice: 30,
	armourClass: 2,
	type: "armour",
	slot: "shield",
	iconPool: [
		"items/armour/shields/shield_09.png",
		"items/armour/shields/shield_10.png",
		"items/armour/shields/shield_11.png",
		"items/armour/shields/shield_12.png",
		"items/armour/shields/shield_13.png",
		"items/armour/shields/shield_14.png",
		"items/armour/shields/shield_15.png",
		"items/armour/shields/shield_16.png",
		"items/armour/shields/shield_17.png",
		"items/armour/shields/shield_18.png",
		"items/armour/shields/shield_19.png",
		"items/armour/shields/shield_20.png",
		"items/armour/shields/shield_32.png",
		"items/armour/shields/shield_33.png",
		"items/armour/shields/shield_34.png",
		"items/armour/shields/shield_35.png",
		"items/armour/shields/shield_36.png",
		"items/armour/shields/shield_37.png",
		"items/armour/shields/shield_38.png",
		"items/armour/shields/Shield_v2_01.png",
		"items/armour/shields/Shield_v2_03.png",
		"items/armour/shields/Shield_v2_04.png",
		"items/armour/shields/Shield_v2_05.png",
		"items/armour/shields/Shield_v2_06.png",
		"items/armour/shields/Shield_v2_07.png",
		"items/armour/shields/Shield_v2_08.png",
		"items/armour/shields/Shield_v2_11.png",
		"items/armour/shields/Shield_v2_13.png",
		"items/armour/shields/Shield_v2_22.png",
		"items/armour/shields/Shield_v2_23.png",
	],
	tags: [],
});
