import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "blessing_of_the_old_gods",
	name: "Blessing of the Old Gods",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-OC-vWqkvavpvmdVpJ3W?alt=media&token=d94590dc-7adb-4cbf-af97-3b0825499b18",
	pool: "unique",
	category: "buff",
	maxUses: 1,
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "fire",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "lightning",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "cold",
					operation: "add",
					value: -25,
					durationTurns: 5,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "fire",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "lightning",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "cold",
					operation: "add",
					value: -37,
					durationTurns: 6,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "fire",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "lightning",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "cold",
					operation: "add",
					value: -50,
					durationTurns: 7,
				},
			],
		},
	],
	tags: [],
});
