import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "divine_protection",
	name: "Divine Protection",
	description: "Invoke celestial safeguard, shielding yourself from harm and dark forces.",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-NhkR-olGXWxxR9Poqo3?alt=media&token=2aa203c7-fff6-4998-b777-bd847ae0773e",
	pool: "cleric",
	category: "buff",
	maxUses: 6,
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "radiant",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "necrotic",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "radiant",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "necrotic",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "radiant",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "necrotic",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
			],
		},
	],
	tags: [],
});
