import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "dueling_stance",
	name: "Dueling Stance",
	description:
		"Adopt a defensive posture that increases armor class while slightly reducing attack power.",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-OHyC611JJw5TvqZwBXp?alt=media&token=0bdf70e9-f832-40ca-b40b-20cc7d2eb379",
	pool: "warrior",
	category: "buff",
	usage: {
		target: "self",
		requiresAttackRoll: false,
		maxUses: 6,
	},
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyStat",
					target: "self",
					stat: "armourClass",
					operation: "add",
					value: 10,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -25,
					durationTurns: 6,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyStat",
					target: "self",
					stat: "armourClass",
					operation: "add",
					value: 15,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -37,
					durationTurns: 7,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyStat",
					target: "self",
					stat: "armourClass",
					operation: "add",
					value: 20,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -50,
					durationTurns: 8,
				},
			],
		},
	],
	tags: [],
});
