import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "fracture",
	name: "Fracture",
	description:
		"Deliver a precise and devastating strike that disrupts the enemy's defenses, reducing their resistance to physical attacks.",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-NKt5eqAEIJYZFNbvK8f?alt=media&token=ec2639b6-7611-42a2-b954-f6bd5a35962c",
	pool: "assassin",
	category: "spell",
	maxUses: 3,
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "slashing",
					operation: "add",
					value: 25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "piercing",
					operation: "add",
					value: 25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "crushing",
					operation: "add",
					value: 25,
					durationTurns: 4,
				},
				{
					type: "damage",
					target: "enemy",
					damageType: "crushing",
					dice: "2d12+11",
					requiresAttackRoll: false,
					save: {
						attribute: "constitution",
						onSuccess: "noEffect",
						dc: {
							base: 8,
							attribute: "constitution",
							includeProficiency: true,
							bonus: 6,
						},
					},
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 4,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "slashing",
					operation: "add",
					value: 38,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "piercing",
					operation: "add",
					value: 38,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "crushing",
					operation: "add",
					value: 38,
					durationTurns: 5,
				},
				{
					type: "damage",
					target: "enemy",
					damageType: "crushing",
					dice: "3d12+15",
					requiresAttackRoll: false,
					save: {
						attribute: "constitution",
						onSuccess: "noEffect",
						dc: {
							base: 8,
							attribute: "constitution",
							includeProficiency: true,
							bonus: 6,
						},
					},
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 5,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "slashing",
					operation: "add",
					value: 50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "piercing",
					operation: "add",
					value: 50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "enemy",
					damageType: "crushing",
					operation: "add",
					value: 50,
					durationTurns: 6,
				},
				{
					type: "damage",
					target: "enemy",
					damageType: "crushing",
					dice: "4d12+20",
					requiresAttackRoll: false,
					save: {
						attribute: "constitution",
						onSuccess: "noEffect",
						dc: {
							base: 8,
							attribute: "constitution",
							includeProficiency: true,
							bonus: 6,
						},
					},
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 6,
				},
			],
		},
	],
	tags: [],
});
