import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "horrifying_visage",
	name: "Horrifying Visage",
	description: "",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-OCJ8msAkFt_vFDtrW5T?alt=media&token=7928e940-5f79-4395-8961-55a901f83713",
	pool: "common",
	category: "debuff",
	usage: {
		target: "enemy",
		requiresAttackRoll: false,
		maxUses: 1,
		save: {
			attribute: "wisdom",
			onSuccess: "noEffect",
			dc: {
				base: 8,
				attribute: "wisdom",
				includeProficiency: true,
				bonus: 3,
			},
		},
	},
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyStat",
					target: "enemy",
					stat: "strength",
					operation: "add",
					value: -4,
					durationTurns: 4,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "dexterity",
					operation: "add",
					value: -4,
					durationTurns: 4,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "constitution",
					operation: "add",
					value: -4,
					durationTurns: 4,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "intelligence",
					operation: "add",
					value: -4,
					durationTurns: 4,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyStat",
					target: "enemy",
					stat: "strength",
					operation: "add",
					value: -6,
					durationTurns: 5,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "dexterity",
					operation: "add",
					value: -6,
					durationTurns: 5,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "constitution",
					operation: "add",
					value: -6,
					durationTurns: 5,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "intelligence",
					operation: "add",
					value: -6,
					durationTurns: 5,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyStat",
					target: "enemy",
					stat: "strength",
					operation: "add",
					value: -8,
					durationTurns: 6,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "dexterity",
					operation: "add",
					value: -8,
					durationTurns: 6,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "constitution",
					operation: "add",
					value: -8,
					durationTurns: 6,
				},
				{
					type: "modifyStat",
					target: "enemy",
					stat: "intelligence",
					operation: "add",
					value: -8,
					durationTurns: 6,
				},
			],
		},
	],
	tags: [],
});
