import { buildSkill } from "../builders/buildSkill";

export default buildSkill({
	id: "will_of_the_deceiver",
	name: "WIll of the Deceiver",
	icon: "https://firebasestorage.googleapis.com/v0/b/monster-manual.appspot.com/o/images%2Fskills%2F-OC8YYxJjpDUyJWCV-HR?alt=media&token=c5c03231-3bea-416e-8360-4a096d032e89",
	pool: "unique",
	category: "debuff",
	maxUses: 2,
	ranks: [
		{
			rank: 1,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "poison",
					operation: "add",
					value: -25,
					durationTurns: 4,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "acid",
					operation: "add",
					value: -25,
					durationTurns: 4,
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 3,
				},
			],
		},
		{
			rank: 2,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -37,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -37,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -37,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "poison",
					operation: "add",
					value: -37,
					durationTurns: 5,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "acid",
					operation: "add",
					value: -37,
					durationTurns: 5,
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 4,
				},
			],
		},
		{
			rank: 3,
			effects: [
				{
					type: "modifyDamage",
					target: "self",
					damageType: "slashing",
					operation: "add",
					value: -50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "crushing",
					operation: "add",
					value: -50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "piercing",
					operation: "add",
					value: -50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "poison",
					operation: "add",
					value: -50,
					durationTurns: 6,
				},
				{
					type: "modifyDamage",
					target: "self",
					damageType: "acid",
					operation: "add",
					value: -50,
					durationTurns: 6,
				},
				{
					type: "applyStatus",
					target: "enemy",
					statusId: "weakened",
					durationTurns: 5,
				},
			],
		},
	],
	tags: [],
});
