export const FINAL_BOSS_BATTLE_NUMBER = 100;
export const BATTLES_PER_ENDLESS_CYCLE = 100;
export const ENDLESS_DAMAGE_INCREASE_PER_CYCLE = 0.5;
export const ENDLESS_DAMAGE_TAKEN_MULTIPLIER_PER_CYCLE = 0.5;
