import { buildClass } from "../builders/buildClass";

export default buildClass({
	id: "warrior",
	order: 1,
	name: "Warrior",
	description: "A durable frontline fighter built around strength and martial weapons.",
	portrait: "classes/portraits/warrior.png",
	enemyPortrait: "classes/enemy_portraits/warrior.png",
	icon: "classes/icons/warrior.png",
	attributes: {
		charisma: 12,
		constitution: 16,
		dexterity: 14,
		intelligence: 10,
		strength: 18,
		wisdom: 10,
	},
	combat: {
		hitDie: "1d10",
		skillIds: ["armour_break"],
		featIds: [],
		tactic: "default",
	},
	proficiencies: {
		armourTypes: ["heavy", "medium", "shield"],
		weaponTypes: [
			"shortsword",
			"longsword",
			"greatsword",
			"handaxe",
			"battleaxe",
			"club",
			"greatclub",
			"hammer",
			"warhammer",
			"mace",
			"morningstar",
			"flail",
			"spear",
			"quarterstaff",
			"bow",
			"crossbow",
		],
		savingThrows: ["strength", "constitution"],
	},
	skillPoolIds: ["fighter", "barbarian"],
	startingEquipment: {
		body: "base_hide_armour",
		mainHand: "base_longsword",
	},
	tags: [],
});
