import type { ContentSpec } from "./types";

export const contentSpecs = [
	{
		type: "skill",
		typeName: "Skill",
		plural: "skills",
		dirName: "skills",
		importPrefix: "ski",
		definitionType: "SkillDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<SkillDefinition, SkillId>",
		referenceRules: [],
	},
	{
		type: "enemy",
		typeName: "Enemy",
		plural: "enemies",
		dirName: "enemies",
		importPrefix: "ene",
		definitionType: "EnemyDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [
			"import type { FeatId } from './featIds';",
			"import type { SkillId } from './skillIds';",
		],
		helperTypeNames: ["WithCombatContentIds", "WithGeneratedId"],
		typeExpression: [
			"Omit<WithGeneratedId<EnemyDefinition, EnemyId>, 'combat'> & {",
			"  combat: WithCombatContentIds<EnemyDefinition['combat'], SkillId, FeatId>;",
			"}",
		].join("\n"),
		referenceRules: [
			{ path: "combat.skillIds[]", targetType: "skill" },
			{ path: "combat.featIds[]", targetType: "feat" },
		],
	},
	{
		type: "item",
		typeName: "Item",
		plural: "items",
		dirName: "items",
		importPrefix: "ite",
		definitionType: "ItemDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<ItemDefinition, ItemId>",
		referenceRules: [],
	},
	{
		type: "class",
		typeName: "Class",
		plural: "classes",
		dirName: "classes",
		importPrefix: "cla",
		definitionType: "ClassDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [
			"import type { FeatId } from './featIds';",
			"import type { ItemId } from './itemIds';",
			"import type { SkillId } from './skillIds';",
		],
		helperTypeNames: ["WithCombatContentIds", "WithEquipmentItemIds", "WithGeneratedId"],
		typeExpression: [
			"Omit<WithGeneratedId<ClassDefinition, ClassId>, 'combat' | 'startingEquipment'> & {",
			"  combat: WithCombatContentIds<ClassDefinition['combat'], SkillId, FeatId>;",
			"  startingEquipment?: WithEquipmentItemIds<NonNullable<ClassDefinition['startingEquipment']>, ItemId>;",
			"}",
		].join("\n"),
		referenceRules: [
			{ path: "combat.skillIds[]", targetType: "skill" },
			{ path: "combat.featIds[]", targetType: "feat" },
			{ path: "startingEquipment.*", targetType: "item" },
		],
	},
	{
		type: "feat",
		typeName: "Feat",
		plural: "feats",
		dirName: "feats",
		importPrefix: "fea",
		definitionType: "FeatDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<FeatDefinition, FeatId>",
		referenceRules: [],
	},
] as const satisfies readonly ContentSpec[];
