import type { ContentSpec } from "./types";

export const contentSpecs = [
	{
		type: "skill",
		typeName: "Skill",
		plural: "skills",
		dirName: "skills",
		importPrefix: "ski",
		definitionType: "SkillDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<SkillDefinition, SkillId>",
		referenceRules: [],
	},
	{
		type: "enemy",
		typeName: "Enemy",
		plural: "enemies",
		dirName: "enemies",
		importPrefix: "ene",
		definitionType: "EnemyDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [
			"import type { FeatId } from './featIds';",
			"import type { SkillId } from './skillIds';",
		],
		helperTypeNames: ["WithCombatContentIds", "WithGeneratedId"],
		typeExpression: [
			"Omit<WithGeneratedId<EnemyDefinition, EnemyId>, 'combat'> & {",
			"  combat: WithCombatContentIds<EnemyDefinition['combat'], SkillId, FeatId>;",
			"}",
		].join("\n"),
		referenceRules: [
			{ path: "combat.skillIds[]", targetType: "skill" },
			{ path: "combat.featIds[]", targetType: "feat" },
		],
	},
	{
		type: "item",
		typeName: "Item",
		plural: "items",
		dirName: "items",
		importPrefix: "ite",
		definitionType: "ItemDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: ["import type { ClassId } from './classIds';"],
		helperTypeNames: ["WithGeneratedId", "WithRestrictedClassIds"],
		typeExpression: "WithRestrictedClassIds<WithGeneratedId<ItemDefinition, ItemId>, ClassId>",
		referenceRules: [{ path: "restrictedToClassIds[]", targetType: "class" }],
	},
	{
		type: "itemBase",
		typeName: "ItemBase",
		plural: "itemBases",
		dirName: "itemBases",
		importPrefix: "iba",
		definitionType: "ItemBaseDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<ItemBaseDefinition, ItemBaseId>",
		referenceRules: [],
	},
	{
		type: "itemAffix",
		typeName: "ItemAffix",
		plural: "itemAffixes",
		dirName: "itemAffixes",
		importPrefix: "iaf",
		definitionType: "ItemAffixDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<ItemAffixDefinition, ItemAffixId>",
		referenceRules: [],
	},
	{
		type: "class",
		typeName: "Class",
		plural: "classes",
		dirName: "classes",
		importPrefix: "cla",
		definitionType: "ClassDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [
			"import type { FeatId } from './featIds';",
			"import type { ItemBaseId } from './itemBaseIds';",
			"import type { SkillId } from './skillIds';",
		],
		helperTypeNames: ["WithCombatContentIds", "WithEquipmentIds", "WithGeneratedId"],
		typeExpression: [
			"Omit<WithGeneratedId<ClassDefinition, ClassId>, 'combat' | 'startingEquipment'> & {",
			"  combat: WithCombatContentIds<ClassDefinition['combat'], SkillId, FeatId>;",
			"  startingEquipment?: WithEquipmentIds<NonNullable<ClassDefinition['startingEquipment']>, ItemBaseId>;",
			"}",
		].join("\n"),
		referenceRules: [
			{ path: "combat.skillIds[]", targetType: "skill" },
			{ path: "combat.featIds[]", targetType: "feat" },
			{ path: "startingEquipment.*", targetType: "itemBase" },
		],
	},
	{
		type: "feat",
		typeName: "Feat",
		plural: "feats",
		dirName: "feats",
		importPrefix: "fea",
		definitionType: "FeatDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<FeatDefinition, FeatId>",
		referenceRules: [],
	},
	{
		type: "achievement",
		typeName: "Achievement",
		plural: "achievements",
		dirName: "achievements",
		importPrefix: "ach",
		definitionType: "AchievementDefinition",
		definitionImportPath: "../schemas",
		typeImportLines: [],
		helperTypeNames: ["WithGeneratedId"],
		typeExpression: "WithGeneratedId<AchievementDefinition, AchievementId>",
		referenceRules: [],
	},
] as const satisfies readonly ContentSpec[];
